#!/usr/bin/env python3
import argparse
import json
import os
import sqlite3
import sys
from typing import Any, Dict, Iterable, List, Optional, Sequence

import psycopg
from psycopg.types.json import Jsonb


def load_env_file(env_path: str = ".env") -> None:
    if not os.path.exists(env_path):
        return

    with open(env_path, "r", encoding="utf-8") as env_file:
        for raw_line in env_file:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("export "):
                line = line[len("export "):].strip()
            if "=" not in line:
                continue

            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key:
                os.environ[key] = value


def _first_non_empty_env(keys: Sequence[str]) -> Optional[str]:
    for key in keys:
        value = os.getenv(key)
        if value and value.strip():
            return value.strip()
    return None


def _parse_conninfo_kv(text: str) -> Dict[str, str]:
    result: Dict[str, str] = {}
    for token in text.split():
        if "=" not in token:
            continue
        key, value = token.split("=", 1)
        key = key.strip().lower()
        value = value.strip().strip('"').strip("'")
        if key and value:
            result[key] = value
    return result


def _quote_conninfo_value(value: str) -> str:
    needs_quotes = any(ch.isspace() or ch in "'\\" for ch in value)
    if not needs_quotes:
        return value
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def _build_conninfo_from_parts(seed: Optional[Dict[str, str]] = None) -> Optional[str]:
    parts = dict(seed or {})

    if "user" not in parts:
        user = _first_non_empty_env(["SUPABASE_DB_USER", "SUPABASE_USER", "PGUSER", "user"])
        if user:
            parts["user"] = user

    if "password" not in parts:
        password = _first_non_empty_env(["SUPABASE_DB_PASSWORD", "SUPABASE_PASSWORD", "PGPASSWORD", "password"])
        if password:
            parts["password"] = password

    if "host" not in parts:
        host = _first_non_empty_env(["SUPABASE_DB_HOST", "SUPABASE_HOST", "PGHOST", "host"])
        if host:
            parts["host"] = host

    if "port" not in parts:
        port = _first_non_empty_env(["SUPABASE_DB_PORT", "SUPABASE_PORT", "PGPORT", "port"])
        if port:
            parts["port"] = port

    if "dbname" not in parts:
        dbname = _first_non_empty_env(["SUPABASE_DB_NAME", "SUPABASE_DB_DBNAME", "PGDATABASE", "dbname"])
        if dbname:
            parts["dbname"] = dbname

    if "sslmode" not in parts:
        sslmode = _first_non_empty_env(["SUPABASE_DB_SSLMODE", "PGSSLMODE", "sslmode"])
        if sslmode:
            parts["sslmode"] = sslmode

    if not parts.get("user") or not parts.get("host"):
        return None

    parts.setdefault("port", "5432")
    parts.setdefault("dbname", "postgres")

    ordered_keys = ["user", "password", "host", "port", "dbname", "sslmode"]
    conninfo_chunks = []
    for key in ordered_keys:
        value = parts.get(key)
        if value:
            conninfo_chunks.append(f"{key}={_quote_conninfo_value(value)}")

    return " ".join(conninfo_chunks)


def resolve_supabase_url() -> Optional[str]:
    direct = _first_non_empty_env(["SUPABASE_DB_URL", "SUPABASE_URL", "SUPABSE_URL"])

    if direct and "://" in direct:
        return direct

    seed: Dict[str, str] = {}
    if direct and "=" in direct:
        seed = _parse_conninfo_kv(direct)

    return _build_conninfo_from_parts(seed)


def parse_json_text(value: Optional[str]) -> Dict[str, Any]:
    if not value:
        return {}
    try:
        parsed = json.loads(value)
        return parsed if isinstance(parsed, dict) else {"value": parsed}
    except json.JSONDecodeError:
        return {}


def normalize_postgres_url(url: str) -> str:
    if url.startswith("postgres://"):
        return "postgresql://" + url[len("postgres://"):]
    return url


def ensure_schema(cursor: psycopg.Cursor) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS schools (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            attributes JSONB,
            raw JSONB
        );

        CREATE TABLE IF NOT EXISTS faculties (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            school_id BIGINT REFERENCES schools(id) ON DELETE SET NULL,
            attributes JSONB,
            raw JSONB
        );

        CREATE TABLE IF NOT EXISTS majors (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            faculty_id BIGINT REFERENCES faculties(id) ON DELETE SET NULL,
            attributes JSONB,
            raw JSONB
        );

        CREATE TABLE IF NOT EXISTS curricula (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            major_id BIGINT REFERENCES majors(id) ON DELETE SET NULL,
            attributes JSONB,
            raw JSONB
        );

        CREATE TABLE IF NOT EXISTS subjects (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            attributes JSONB,
            raw JSONB
        );

        CREATE TABLE IF NOT EXISTS curriculum_subjects (
            curricula_id BIGINT REFERENCES curricula(id) ON DELETE CASCADE,
            subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
            link_attributes JSONB,
            PRIMARY KEY (curricula_id, subject_id)
        );

        CREATE INDEX IF NOT EXISTS idx_faculties_school_id ON faculties(school_id);
        CREATE INDEX IF NOT EXISTS idx_majors_faculty_id ON majors(faculty_id);
        CREATE INDEX IF NOT EXISTS idx_curricula_major_id ON curricula(major_id);
        CREATE INDEX IF NOT EXISTS idx_curriculum_subjects_curricula_id ON curriculum_subjects(curricula_id);
        CREATE INDEX IF NOT EXISTS idx_curriculum_subjects_subject_id ON curriculum_subjects(subject_id);
        """
    )


def truncate_target_tables(cursor: psycopg.Cursor) -> None:
    cursor.execute(
        """
        TRUNCATE TABLE
            curriculum_subjects,
            subjects,
            curricula,
            majors,
            faculties,
            schools
        RESTART IDENTITY CASCADE;
        """
    )


def sync_identity_sequence(cursor: psycopg.Cursor, table: str) -> None:
    cursor.execute(
        f"""
        SELECT setval(
            pg_get_serial_sequence('{table}', 'id'),
            COALESCE((SELECT MAX(id) FROM {table}), 1),
            (SELECT COUNT(*) > 0 FROM {table})
        );
        """
    )


def fetch_rows(sqlite_conn: sqlite3.Connection, query: str) -> List[sqlite3.Row]:
    return list(sqlite_conn.execute(query).fetchall())


def to_jsonb(value: Optional[str]) -> Jsonb:
    return Jsonb(parse_json_text(value))


def upsert_entities(
    cursor: psycopg.Cursor,
    rows: Iterable[Sequence[Any]],
    insert_sql: str,
) -> int:
    payload = list(rows)
    if not payload:
        return 0
    cursor.executemany(insert_sql, payload)
    return len(payload)


def migrate(sqlite_db_path: str, supabase_db_url: str, truncate: bool) -> None:
    if not os.path.exists(sqlite_db_path):
        raise FileNotFoundError(f"SQLite file not found: {sqlite_db_path}")

    pg_url = normalize_postgres_url(supabase_db_url)

    sqlite_conn = sqlite3.connect(sqlite_db_path)
    sqlite_conn.row_factory = sqlite3.Row

    try:
        with psycopg.connect(pg_url, autocommit=False) as pg_conn:
            with pg_conn.cursor() as cursor:
                ensure_schema(cursor)

                if truncate:
                    truncate_target_tables(cursor)

                schools = fetch_rows(sqlite_conn, "SELECT id, attributes, raw FROM schools ORDER BY id")
                school_ids = {int(row["id"]) for row in schools}
                school_payload = [(row["id"], to_jsonb(row["attributes"]), to_jsonb(row["raw"])) for row in schools]
                school_count = upsert_entities(
                    cursor,
                    school_payload,
                    """
                    INSERT INTO schools (id, attributes, raw)
                    VALUES (%s, %s, %s)
                    ON CONFLICT (id) DO UPDATE
                    SET attributes = EXCLUDED.attributes,
                        raw = EXCLUDED.raw;
                    """,
                )

                faculties = fetch_rows(
                    sqlite_conn,
                    "SELECT id, school_id, attributes, raw FROM faculties ORDER BY id",
                )
                faculty_ids = {int(row["id"]) for row in faculties}
                faculty_payload = [
                    (
                        row["id"],
                        row["school_id"] if row["school_id"] in school_ids else None,
                        to_jsonb(row["attributes"]),
                        to_jsonb(row["raw"]),
                    )
                    for row in faculties
                ]
                faculty_count = upsert_entities(
                    cursor,
                    faculty_payload,
                    """
                    INSERT INTO faculties (id, school_id, attributes, raw)
                    VALUES (%s, %s, %s, %s)
                    ON CONFLICT (id) DO UPDATE
                    SET school_id = EXCLUDED.school_id,
                        attributes = EXCLUDED.attributes,
                        raw = EXCLUDED.raw;
                    """,
                )

                majors = fetch_rows(
                    sqlite_conn,
                    "SELECT id, faculty_id, attributes, raw FROM majors ORDER BY id",
                )
                major_ids = {int(row["id"]) for row in majors}
                major_payload = [
                    (
                        row["id"],
                        row["faculty_id"] if row["faculty_id"] in faculty_ids else None,
                        to_jsonb(row["attributes"]),
                        to_jsonb(row["raw"]),
                    )
                    for row in majors
                ]
                major_count = upsert_entities(
                    cursor,
                    major_payload,
                    """
                    INSERT INTO majors (id, faculty_id, attributes, raw)
                    VALUES (%s, %s, %s, %s)
                    ON CONFLICT (id) DO UPDATE
                    SET faculty_id = EXCLUDED.faculty_id,
                        attributes = EXCLUDED.attributes,
                        raw = EXCLUDED.raw;
                    """,
                )

                curricula = fetch_rows(
                    sqlite_conn,
                    "SELECT id, major_id, attributes, raw FROM curricula ORDER BY id",
                )
                curriculum_ids = {int(row["id"]) for row in curricula}
                curriculum_payload = [
                    (
                        row["id"],
                        row["major_id"] if row["major_id"] in major_ids else None,
                        to_jsonb(row["attributes"]),
                        to_jsonb(row["raw"]),
                    )
                    for row in curricula
                ]
                curriculum_count = upsert_entities(
                    cursor,
                    curriculum_payload,
                    """
                    INSERT INTO curricula (id, major_id, attributes, raw)
                    VALUES (%s, %s, %s, %s)
                    ON CONFLICT (id) DO UPDATE
                    SET major_id = EXCLUDED.major_id,
                        attributes = EXCLUDED.attributes,
                        raw = EXCLUDED.raw;
                    """,
                )

                subjects = fetch_rows(sqlite_conn, "SELECT id, attributes, raw FROM subjects ORDER BY id")
                subject_ids = {int(row["id"]) for row in subjects}
                subject_payload = [(row["id"], to_jsonb(row["attributes"]), to_jsonb(row["raw"])) for row in subjects]
                subject_count = upsert_entities(
                    cursor,
                    subject_payload,
                    """
                    INSERT INTO subjects (id, attributes, raw)
                    VALUES (%s, %s, %s)
                    ON CONFLICT (id) DO UPDATE
                    SET attributes = EXCLUDED.attributes,
                        raw = EXCLUDED.raw;
                    """,
                )

                links = fetch_rows(
                    sqlite_conn,
                    "SELECT curricula_id, subject_id, link_attributes FROM curriculum_subjects ORDER BY curricula_id, subject_id",
                )
                link_payload = [
                    (row["curricula_id"], row["subject_id"], to_jsonb(row["link_attributes"]))
                    for row in links
                    if row["curricula_id"] in curriculum_ids and row["subject_id"] in subject_ids
                ]
                skipped_links = len(links) - len(link_payload)
                link_count = upsert_entities(
                    cursor,
                    link_payload,
                    """
                    INSERT INTO curriculum_subjects (curricula_id, subject_id, link_attributes)
                    VALUES (%s, %s, %s)
                    ON CONFLICT (curricula_id, subject_id) DO UPDATE
                    SET link_attributes = EXCLUDED.link_attributes;
                    """,
                )

                for table in ("schools", "faculties", "majors", "curricula", "subjects"):
                    sync_identity_sequence(cursor, table)

            pg_conn.commit()

    finally:
        sqlite_conn.close()

    print("Migration completed.")
    print(f"- schools: {school_count}")
    print(f"- faculties: {faculty_count}")
    print(f"- majors: {major_count}")
    print(f"- curricula: {curriculum_count}")
    print(f"- subjects: {subject_count}")
    print(f"- curriculum_subjects: {link_count}")
    if skipped_links:
        print(f"- skipped invalid curriculum_subjects links: {skipped_links}")


def main() -> None:
    load_env_file()

    parser = argparse.ArgumentParser(description="Migrate SQLite syllabus.db data to Supabase PostgreSQL")
    parser.add_argument("--sqlite-db", default="database/syllabus.db", help="Path to SQLite DB")
    parser.add_argument(
        "--supabase-db-url",
        default=resolve_supabase_url(),
        help=(
            "Supabase PostgreSQL connection string. Supports URL, key-value conninfo, "
            "or values in .env (SUPABASE_DB_URL/SUPABASE_URL/SUPABSE_URL or user/password/host/port/dbname)."
        ),
    )
    parser.add_argument(
        "--truncate",
        action="store_true",
        help="Truncate target tables before migration",
    )

    args = parser.parse_args()

    if not args.supabase_db_url:
        print(
            "Missing Supabase DB URL. Pass --supabase-db-url or set SUPABASE_DB_URL "
            "(SUPABASE_URL/SUPABSE_URL are also supported) in .env."
        )
        sys.exit(1)

    try:
        migrate(args.sqlite_db, args.supabase_db_url, args.truncate)
    except Exception as exc:
        print(f"Migration failed: {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
